Serhei poluyan 1 2 3
tamkovich/tms-python-spring pull request #28
Opened 2021-05-24 11:03 UTC by pevlens

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8).
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks.
- [ ] my PR made from the fork feature branch to appropriate branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore.

2021-05-24 11:28 UTC, pevlens commented
HW

2021-05-25 06:42 UTC, tamkovich commented on src/task_1_1.py
> +a = 4.6
добавь описание задач в шапку

2021-05-25 06:43 UTC, tamkovich commented on src/task_1_2.py
> +from math import fabs
Сделай задание без использования math

2021-05-25 06:43 UTC, tamkovich commented on src/task_1_3.py
> +square = length**2
https://github.com/tamkovich/tms-python-spring/blob/hw_reviews/src/Common.md пункт 24

2021-05-25 06:44 UTC, tamkovich commented on src/task_1_4.py
> +Geometric_Mean = product_numbers_1 / len(last)
именуй переменные с маленькой буквы

```suggestion
geometric_mean = product_numbers_1 / len(last)
```

2021-05-25 06:44 UTC, tamkovich commented on src/task_1_5.py
> +from math import sqrt
без math

2021-05-25 06:44 UTC, tamkovich requested changes
.

2021-06-22 15:27 UTC, tamkovich commented
 Разбей на разные ветки домашки

2021-06-22 15:27 UTC, closed without merging